# Use root/example as user/password credentials
version: '3.1'

services:

  mongo:
    image: mongo
    restart: always
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: localmongo
      MONGO_INITDB_ROOT_PASSWORD: localmongo

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8281:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: localmongo
      ME_CONFIG_MONGODB_ADMINPASSWORD: localmongo

  basic-expenses:
    image: dr34mh4ck/basicexpenses-app:latest
    ports:
      - 9191:9191
    environment:
      MONGO_USER: localmongo
      MONGO_PASS: localmongo
      MONGO_HOST: mongo

  prometheus:
    image: prom/prometheus:latest
    volumes:
      - ./prometheus.yaml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"

  grafana:
    image: grafana/grafana
    ports:
      - 3000:3000
    volumes:
      - ./datasource.yml:/etc/grafana/provisioning/datasources/datasource.yml
    depends_on:
      - prometheus