server:
  port: 9191

spring:
  data:
    mongodb:
      uri: mongodb://${MONGO_USER}:${MONGO_PASS}@${MONGO_HOST}:27017/expenses_db?authSource=admin

management:
  endpoints:
    web:
      exposure:
        include: "*"

#logging:
 # level:
  #  root: DEBUG
