apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
data:
  prometheus.yml: |
    scrape_configs:
      - job_name: 'application'
        metrics_path: 'actuator/prometheus'
        static_configs:
          - targets: ['basic-expenses:9191']

